name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        uses: huggingface/hub-sync@main
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: hassanraza04/ds_final_proj
          repo_type: space
          hf_token: ${{ secrets.HF_TOKEN }}
